import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const kyoboHandwriting = localFont({
  src: "../../public/fonts/KyoboHandwriting2019.otf",
  display: "swap",
  variable: "--font-kyobo-handwriting",
});

export const metadata: Metadata = {
  title: "Book Snap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${kyoboHandwriting.variable}`}>
      <body className="bg-amber-50">{children}</body>
    </html>
  );
}
