import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ReactQueryProvider from "@/hooks/useReactQueryProvider";

const kyoboHandwriting = localFont({
  src: "../../public/fonts/KyoboHandwriting2019.otf",
  display: "swap",
  variable: "--font-kyobo-handwriting",
});

export const metadata: Metadata = {
  title: "Book Snap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${kyoboHandwriting.variable}`}>
      <body className="bg-amber-50 font-kyobo-handwriting">
        <ReactQueryProvider>
          {children}
          {modal}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
